#+OPTIONS: ':nil *:t -:t ::t <:t H:3 \n:nil ^:t arch:headline
#+OPTIONS: author:t broken-links:nil c:nil creator:nil
#+OPTIONS: d:(not "LOGBOOK") date:t e:t email:nil f:t inline:t num:nil
#+OPTIONS: p:nil pri:nil prop:nil stat:t tags:t tasks:t tex:t
#+OPTIONS: timestamp:t title:t toc:t todo:t |:t
#+TITLE: documentation
#+AUTHOR: Andrew M Davis, PhD
#+EMAIL: @reconmaster:matrix.org
#+LANGUAGE: en
#+SELECT_TAGS: export
#+EXCLUDE_TAGS: noexport
#+CREATOR: Emacs 26.1 (Org mode 9.1.13)
#+FILETAGS: 気, ki, doc
Objective: [[https://en.wikipedia.org/wiki/Documentation][documentation]]
* Introduction
These documents are the underlying source code that run Operation
Mountaintop. These documents are populated with TODO items that need
to be broken into smaller NEXT items that are achievable so that we
can eventually get things DONE.
* TODO [#A] [[file:conops.org][Concept of Operations (CONOPS)]]
This document provides an overiview of the Operation design. This
provides the blueprint for how we plan to exectue this Operation once
the intial planning phase is complete.
** NEXT [#A] break the CONOPS into TODO items to meet goals
* TODO [#B] [[file:agenda.org][Agenda]]
This document provides agenda items that don't fit in the other
document categories.
* TODO [#A] [[file:aikido.org][Aikido]]
The Aikido document provides our agenda for how to spread the Art of
Peace.
